services:
  db:
    image: mysql:8.0
    container_name: support_db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: support_triage
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  api:
    build:
      context: .
      target: runtime
    container_name: support_api
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env

  test:
    build:
      context: .
      target: test
    container_name: support_test
    depends_on:
      - db
    env_file:
      - .env

volumes:
  mysql_data:
